--liquibase formatted sql

--changeset ashvedov:1
CREATE TABLE IF NOT EXISTS users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

--changeset ashvedov:2
CREATE TABLE IF NOT EXISTS company
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_company PRIMARY KEY (id)
);